source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLSocialSignIn_Example', :exclusive => true do
  pod 'PLSocialSignIn', :path => '../'
end

target 'PLSocialSignIn_Tests', :exclusive => true do
  pod 'PLSocialSignIn', :path => '../'

  
end
